version: '3.8'

services:
  db:
    image: postgres:16
    container_name: blizzard-db
    restart: always
    environment:
      POSTGRES_DB: blizzard
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  blizzard-bot:
    build: .
    container_name: blizzard-bot
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}

volumes:
  postgres_data:
